language: python
python: 3.8

env:
  global:
    CC_TEST_REPORTER_ID=3edb8f54b28b6e9b179971adc38c341ef70fd107614fcbeaaa1a400e416c6f98

before_install:
  - pip install poetry

install:
  - make install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test

after_script:
  - ./cc-test-reporter after-build -t coverage.py -d --exit-code $TRAVIS_TEST_RESULT
